language: node_js
node_js:
  - lts/*
env:
    - DEBUG=garmin:*
script:
    - npm run activity-build
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  on:
    branch: main