language: node_js
node_js:
  - lts/*
env:
    - DEBUG=garmin:*
script:
    - npm run build-activity
os: linux
dist: xenial
deploy:
  edge: true
  provider: pages
  strategy: git
  cleanup: false
  token: $GITHUB_TOKEN
  keep_history: true
  on:
    branch: gh-pages