language: node_js
node_js:
  - lts/*
env:
    - DEBUG=garmin:*
script:
    - npm run build-activity
os: linux
dist: xenial
# Build all branches, *including* gh-pages:
branches:
  only:
  - gh-pages
deploy:
  edge: true
  provider: pages
  strategy: git
  cleanup: false
  token: $GITHUB_TOKEN
  keep_history: true