language: node_js
node_js:
  - lts/*
env:
    - DEBUG=garmin:*
script:
    - npm run activity-build
os: linux
dist: xenial
deploy:
  edge: true
  provider: pages:git
  cleanup: false
  strategy: git
  token: $GITHUB_TOKEN
  keep_history: true
  on:
    branch: main